import React from "react";
import {
  Printer,
  Download,
  Copy,
  BadgeCheck,
  CheckCheck,
  Check,
  Car,
  KeyRound,
  PlaneLanding,
  PlaneTakeoff,
  Phone,
  MessageSquare,
  Mail,
  Gauge,
  Infinity as InfinityIcon,
  Armchair,
  Settings,
  Star,
  CheckCircle2,
  ShieldCheck,
  Clock,
  Shield,
  IdCard,
  MapPin,
  RotateCcw,
  Info,
  ArrowLeft,
  ArrowRight,
  CreditCard,
  Lock,
} from "lucide-react";
import type { ConfirmationIconKey } from "../../types/bookingConfirmation";

const ICONS: Record<ConfirmationIconKey, React.ComponentType<{ className?: string }>> = {
  print: Printer,
  download: Download,
  copy: Copy,
  verified: BadgeCheck,
  done: CheckCheck,
  check: Check,
  car: Car,
  key: KeyRound,
  land: PlaneLanding,
  takeoff: PlaneTakeoff,
  call: Phone,
  sms: MessageSquare,
  mail: Mail,
  speed: Gauge,
  infinity: InfinityIcon,
  seat: Armchair,
  settings: Settings,
  star: Star,
  checkCircle: CheckCircle2,
  encrypted: ShieldCheck,
  clock: Clock,
  gps: Shield,
  shield: Lock,
  badge: IdCard,
  location: MapPin,
  restart: RotateCcw,
  info: Info,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  credit: CreditCard,
  security: Lock,
};

export const ConfirmationIcon: React.FC<{ name: ConfirmationIconKey; className?: string }> = ({
  name,
  className,
}) => {
  const Icon = ICONS[name];
  return <Icon className={className} />;
};