import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router";
import { useTranslation } from "react-i18next";
import { CalendarDays, Camera, CheckCircle2, ChevronRight, Eye, EyeOff, Home, KeyRound, LockKeyhole, Mail, Phone, Save, ShieldCheck, UserRound } from "lucide-react";
import { useAuth } from "../context/useAuth";
import { authApi } from "../lib/authApi";
import { ApiError } from "../lib/apiClient";
import { userPhotoUrl } from "../lib/customerView";

const text = {
  en: { home:"Home", account:"My account", title:"My Profile", titleAlt:"Profile and account settings", intro:"Manage the personal and contact information used for your NexRide reservations.", profile:"My Profile", rentals:"My Bookings / Rentals", securityNav:"Security & Password", customer:"NexRide customer", member:"Member since", photoTitle:"Profile Photo", photoText:"Your photo helps rental companies identify you at vehicle handover.", ready:"Ready", selected:"New photo selected", upload:"Upload new photo", photoHelp:"JPG or PNG. Maximum file size 5 MB.", personal:"Personal Information", personalText:"Update the details used for booking confirmations and rental receipts.", name:"Full name", email:"Email address", phone:"Phone number", cancel:"Cancel", save:"Save changes", saving:"Saving…", saved:"Profile updated successfully.", security:"Security & Password", securityText:"Change your password using your current account password.", current:"Current password", next:"New password", confirm:"Confirm new password", help:"Use at least 8 characters.", update:"Update password", updating:"Updating…", passwordSaved:"Password updated successfully.", required:"Complete all password fields.", short:"The new password must contain at least 8 characters.", mismatch:"The new passwords do not match.", loadError:"We could not refresh your profile. The saved session details are shown.", fileError:"Choose a JPG or PNG image smaller than 5 MB.", error:"Something went wrong. Please try again." },
  ar: { home:"الرئيسية", account:"حسابي", title:"ملفي الشخصي", titleAlt:"الملف الشخصي وإعدادات الحساب", intro:"إدارة البيانات الشخصية ومعلومات التواصل المستخدمة في حجوزات نكس رايد.", profile:"ملفي الشخصي", rentals:"حجوزاتي وإيجاراتي", securityNav:"الأمان وكلمة المرور", customer:"عميل نكس رايد", member:"عضو منذ", photoTitle:"صورة الملف الشخصي", photoText:"تساعد صورتك شركة التأجير على التعرف عليك عند تسليم المركبة.", ready:"جاهزة", selected:"تم اختيار صورة جديدة", upload:"رفع صورة جديدة", photoHelp:"JPG أو PNG. الحد الأقصى 5 ميجابايت.", personal:"المعلومات الشخصية", personalText:"حدّث البيانات المستخدمة في تأكيدات الحجز وإيصالات الإيجار.", name:"الاسم الكامل", email:"البريد الإلكتروني", phone:"رقم الهاتف", cancel:"إلغاء", save:"حفظ التغييرات", saving:"جارٍ الحفظ…", saved:"تم تحديث الملف الشخصي بنجاح.", security:"الأمان وكلمة المرور", securityText:"غيّر كلمة المرور باستخدام كلمة مرور حسابك الحالية.", current:"كلمة المرور الحالية", next:"كلمة المرور الجديدة", confirm:"تأكيد كلمة المرور الجديدة", help:"استخدم 8 أحرف على الأقل.", update:"تحديث كلمة المرور", updating:"جارٍ التحديث…", passwordSaved:"تم تحديث كلمة المرور بنجاح.", required:"أكمل جميع حقول كلمة المرور.", short:"يجب ألا تقل كلمة المرور الجديدة عن 8 أحرف.", mismatch:"كلمتا المرور الجديدتان غير متطابقتين.", loadError:"تعذر تحديث الملف. نعرض بيانات الجلسة المحفوظة.", fileError:"اختر صورة JPG أو PNG أصغر من 5 ميجابايت.", error:"حدث خطأ. يرجى المحاولة مرة أخرى." },
} as const;

type Notice = { kind: "success" | "error"; text: string } | null;
type IconType = React.ComponentType<{ className?: string }>;

const NoticeBanner = ({ notice }: { notice: Notice }) => notice ? <div className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold ${notice.kind === "success" ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{notice.kind === "success" && <CheckCircle2 className="size-4 shrink-0" />}{notice.text}</div> : null;

const Field = ({ icon: Icon, label, dir, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { icon: IconType; label: string }) => {
  const isLtr = dir === "ltr";
  return <label className="grid gap-2"><span className="text-sm font-bold text-[#0B1C30]">{label}</span><span className="relative block" dir={dir}><Icon className={`pointer-events-none absolute top-1/2 z-10 size-4 -translate-y-1/2 text-slate-400 ${isLtr ? "left-4" : "right-4"}`} /><input {...props} dir={dir} className={`h-12 w-full rounded-xl border-0 bg-[#EFF4FF] text-sm font-semibold text-[#0B1C30] outline-none ring-1 ring-transparent transition focus:bg-white focus:ring-2 focus:ring-blue-600 ${isLtr ? "pl-11 pr-4" : "pl-4 pr-11"}`} /></span></label>;
};

export const MyProfilePage: React.FC = () => {
  const { i18n } = useTranslation();
  const { user, updateUser, adoptSession } = useAuth();
  const c = i18n.language.startsWith("ar") ? text.ar : text.en;
  const fileInput = useRef<HTMLInputElement>(null);
  const securityRef = useRef<HTMLElement>(null);
  const previewUrlRef = useRef("");
  const [form, setForm] = useState({ name:user?.name ?? "", email:user?.email ?? "", phoneNumber:user?.phoneNumber ?? "" });
  const [photo, setPhoto] = useState<File | null>(null);
  const [preview, setPreview] = useState("");
  const [profileNotice, setProfileNotice] = useState<Notice>(null);
  const [saving, setSaving] = useState(false);
  const [passwords, setPasswords] = useState({ passwordCurrent:"", password:"", passwordConfirm:"" });
  const [passwordNotice, setPasswordNotice] = useState<Notice>(null);
  const [passwordBusy, setPasswordBusy] = useState(false);
  const [showPasswords, setShowPasswords] = useState(false);

  const setFormFromUser = useCallback((next = user) => { if (next) setForm({ name:next.name, email:next.email, phoneNumber:next.phoneNumber }); }, [user]);
  useEffect(() => { let active = true; authApi.me().then(({data}) => { if (active) { updateUser(data.user); setFormFromUser(data.user); } }).catch(() => active && setProfileNotice({kind:"error",text:c.loadError})); return () => { active = false; }; }, [c.loadError, setFormFromUser, updateUser]);
  useEffect(() => () => { if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current); }, []);
  const initials = useMemo(() => (user?.name ?? "N R").split(/\s+/).filter(Boolean).slice(0,2).map((part) => part[0]).join("").toUpperCase(), [user?.name]);
  if (!user) return null;
  const avatar = preview || userPhotoUrl(user.photo);
  const joined = user.createdAt ? new Intl.DateTimeFormat(i18n.language,{month:"long",year:"numeric"}).format(new Date(user.createdAt)) : "—";
  const dirty = Boolean(photo) || form.name !== user.name || form.email !== user.email || form.phoneNumber !== user.phoneNumber;

  const clearSelectedPhoto = () => { if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current); previewUrlRef.current = ""; setPreview(""); setPhoto(null); };
  const selectPhoto = (file?: File) => { if (!file) return; if (!["image/jpeg","image/png"].includes(file.type) || file.size > 5*1024*1024) { setProfileNotice({kind:"error",text:c.fileError}); return; } if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current); const url = URL.createObjectURL(file); previewUrlRef.current = url; setPreview(url); setPhoto(file); setProfileNotice(null); };
  const reset = () => { setFormFromUser(); clearSelectedPhoto(); setProfileNotice(null); };
  const saveProfile = async (event:React.FormEvent) => { event.preventDefault(); setSaving(true); setProfileNotice(null); try { const payload = new FormData(); payload.append("name",form.name.trim()); payload.append("email",form.email.trim()); payload.append("phoneNumber",form.phoneNumber.trim()); if(photo) payload.append("photo",photo); const {data}=await authApi.updateProfile(payload); updateUser(data.user); setFormFromUser(data.user); clearSelectedPhoto(); setProfileNotice({kind:"success",text:c.saved}); } catch(error) { setProfileNotice({kind:"error",text:error instanceof ApiError?error.message:c.error}); } finally { setSaving(false); } };
  const savePassword = async (event:React.FormEvent) => { event.preventDefault(); setPasswordNotice(null); if(!passwords.passwordCurrent||!passwords.password||!passwords.passwordConfirm) return setPasswordNotice({kind:"error",text:c.required}); if(passwords.password.length<8) return setPasswordNotice({kind:"error",text:c.short}); if(passwords.password!==passwords.passwordConfirm) return setPasswordNotice({kind:"error",text:c.mismatch}); setPasswordBusy(true); try { const result=await authApi.updatePassword(passwords); adoptSession(result.token,result.data.user); setPasswords({passwordCurrent:"",password:"",passwordConfirm:""}); setPasswordNotice({kind:"success",text:c.passwordSaved}); } catch(error) { setPasswordNotice({kind:"error",text:error instanceof ApiError?error.message:c.error}); } finally { setPasswordBusy(false); } };

  return <main className="min-h-screen bg-[#F8F9FF] pb-16 pt-24 md:pt-28"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-4 sm:px-6 lg:px-8">
    <header className="space-y-4"><nav className="flex flex-wrap items-center gap-2 text-xs font-semibold text-slate-500"><Link to="/" className="flex items-center gap-1 hover:text-blue-600"><Home className="size-3.5" />{c.home}</Link><span>/</span><span>{c.account}</span><span>/</span><span className="font-bold text-blue-600">{c.profile}</span></nav><div className="flex flex-col gap-2 md:flex-row md:items-end md:gap-4"><h1 className="text-3xl font-black tracking-tight text-[#0B1C30] md:text-4xl">{c.title}</h1><span className="pb-1 text-lg font-semibold text-slate-500">{c.titleAlt}</span></div><p className="max-w-2xl text-sm leading-6 text-slate-600">{c.intro}</p></header>
    <div className="grid items-start gap-8 lg:grid-cols-12">
      <aside className="grid gap-6 lg:col-span-4 xl:col-span-3"><section className="rounded-2xl bg-white p-6 shadow-[0_4px_20px_-2px_rgba(15,23,42,.06)]"><div className="flex items-center gap-4"><Avatar src={avatar} initials={initials} name={user.name} size="small" /><div className="min-w-0"><h2 className="truncate text-lg font-black text-[#0B1C30]">{user.name}</h2><p className="truncate text-xs font-semibold text-blue-600" dir="ltr">{user.email}</p><p className="mt-1 text-xs text-slate-500">{c.customer}</p></div></div><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#EFF4FF] px-3 py-3"><CalendarDays className="size-4 text-blue-600" /><div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{c.member}</p><p className="text-sm font-bold text-[#0B1C30]">{joined}</p></div></div></section>
      <nav className="grid gap-1.5 rounded-2xl bg-white p-3 shadow-[0_4px_20px_-2px_rgba(15,23,42,.06)]"><div className="flex items-center justify-between rounded-xl bg-[#EFF4FF] px-4 py-3 font-bold text-blue-600"><span className="flex items-center gap-3"><UserRound className="size-5" />{c.profile}</span><span className="h-6 w-1.5 rounded-full bg-blue-600" /></div><Link to="/my-bookings" className="flex items-center justify-between rounded-xl px-4 py-3 font-semibold text-slate-600 hover:bg-[#EFF4FF] hover:text-blue-600"><span className="flex items-center gap-3"><CalendarDays className="size-5" />{c.rentals}</span><ChevronRight className="size-4 rtl:rotate-180" /></Link><button type="button" onClick={() => securityRef.current?.scrollIntoView({behavior:"smooth",block:"start"})} className="flex items-center justify-between rounded-xl px-4 py-3 text-start font-semibold text-slate-600 hover:bg-[#EFF4FF] hover:text-blue-600"><span className="flex items-center gap-3"><ShieldCheck className="size-5" />{c.securityNav}</span><ChevronRight className="size-4 rtl:rotate-180" /></button></nav></aside>
      <div className="grid gap-6 lg:col-span-8 xl:col-span-9">
        <section className="rounded-2xl bg-white p-6 shadow-[0_4px_20px_-2px_rgba(15,23,42,.06)] md:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="text-xl font-black text-[#0B1C30]">{c.photoTitle}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{c.photoText}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#E5EEFF] px-3 py-1 text-xs font-bold text-blue-700"><span className="size-2 rounded-full bg-blue-600" />{photo?c.selected:c.ready}</span></div><div className="mt-7 flex flex-col items-center gap-6 sm:flex-row sm:items-start"><div className="relative size-28 shrink-0"><Avatar src={avatar} initials={initials} name={user.name} size="large" /><button type="button" onClick={() => fileInput.current?.click()} className="absolute bottom-0 end-0 z-20 grid size-9 place-items-center rounded-full bg-blue-600 text-white shadow-lg hover:bg-blue-700"><Camera className="size-4" /></button></div><div className="grid justify-items-center gap-3 pt-2 sm:justify-items-start"><input ref={fileInput} type="file" accept="image/jpeg,image/png" className="hidden" onChange={(e)=>selectPhoto(e.target.files?.[0])}/><button type="button" onClick={()=>fileInput.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-[0_4px_12px_rgba(37,99,235,.25)] hover:bg-blue-700"><Camera className="size-4" />{c.upload}</button><p className="text-xs text-slate-500">{c.photoHelp}</p></div></div></section>
        <form onSubmit={saveProfile} className="rounded-2xl bg-white p-6 shadow-[0_4px_20px_-2px_rgba(15,23,42,.06)] md:p-8"><h2 className="text-xl font-black text-[#0B1C30]">{c.personal}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{c.personalText}</p><div className="mt-7 grid gap-5 md:grid-cols-2"><Field icon={UserRound} label={c.name} value={form.name} required onChange={(e)=>setForm({...form,name:e.target.value})}/><Field icon={Phone} label={c.phone} value={form.phoneNumber} required dir="ltr" onChange={(e)=>setForm({...form,phoneNumber:e.target.value})}/><div className="md:col-span-2"><Field icon={Mail} label={c.email} value={form.email} type="email" required dir="ltr" onChange={(e)=>setForm({...form,email:e.target.value})}/></div></div><div className="mt-7 grid gap-4 border-t border-slate-100 pt-6 sm:grid-cols-[1fr_auto] sm:items-center"><NoticeBanner notice={profileNotice}/><div className="flex justify-end gap-3"><button type="button" disabled={!dirty||saving} onClick={reset} className="rounded-xl px-5 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100 disabled:opacity-40">{c.cancel}</button><button disabled={!dirty||saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 text-sm font-black text-white shadow-md hover:bg-blue-700 disabled:opacity-45"><Save className="size-4" />{saving?c.saving:c.save}</button></div></div></form>
        <section ref={securityRef} className="scroll-mt-28 rounded-2xl bg-white p-6 shadow-[0_4px_20px_-2px_rgba(15,23,42,.06)] md:p-8"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#E5EEFF] text-blue-700"><KeyRound className="size-5" /></span><div><h2 className="text-xl font-black text-[#0B1C30]">{c.security}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{c.securityText}</p></div></div><form onSubmit={savePassword} className="mt-7 grid gap-5">{(["passwordCurrent","password","passwordConfirm"] as const).map((field,index)=><label key={field} className="grid gap-2"><span className="text-sm font-bold text-[#0B1C30]">{index===0?c.current:index===1?c.next:c.confirm}</span><span className="relative block" dir="ltr"><LockKeyhole className="pointer-events-none absolute left-4 top-1/2 z-10 size-4 -translate-y-1/2 text-slate-400"/><input dir="ltr" type={showPasswords?"text":"password"} value={passwords[field]} autoComplete={index===0?"current-password":"new-password"} onChange={(e)=>setPasswords({...passwords,[field]:e.target.value})} className="h-12 w-full rounded-xl border-0 bg-[#EFF4FF] py-0 pl-11 pr-12 text-sm font-semibold text-[#0B1C30] outline-none focus:bg-white focus:ring-2 focus:ring-blue-600"/><button type="button" onClick={()=>setShowPasswords((v)=>!v)} className="absolute right-4 top-1/2 z-10 -translate-y-1/2 text-slate-400 hover:text-blue-600">{showPasswords?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></span>{index===1&&<span className="text-xs text-slate-500">{c.help}</span>}</label>)}<div className="grid gap-4 border-t border-slate-100 pt-6 sm:grid-cols-[1fr_auto] sm:items-center"><NoticeBanner notice={passwordNotice}/><button disabled={passwordBusy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0B1C30] px-6 py-3 text-sm font-black text-white hover:bg-slate-800 disabled:opacity-50"><KeyRound className="size-4" />{passwordBusy?c.updating:c.update}</button></div></form></section>
      </div>
    </div>
  </div></main>;
};

const Avatar=({src,initials,name,size}:{src:string;initials:string;name:string;size:"small"|"large"}) => {
  const dimensions = size === "large" ? "h-28 w-28" : "h-16 w-16";
  return <div className={`relative ${dimensions} shrink-0 overflow-hidden rounded-full bg-blue-600 text-white shadow-sm`}>{src?<img src={src} alt={name} className="absolute inset-0 block h-full w-full max-w-full rounded-full object-cover"/>:<span className="grid h-full w-full place-items-center text-xl font-black">{initials}</span>}</div>;
};
export default MyProfilePage;
